### ISSUE TITLE
Ceiling Squash optimization

### ISSUE THREAD

**Issue by shifatkhan** [WillyNgo/Dodge#2]
### Issue
The issue right now is that I'm trying to optimize the way the ceiling squashing mechanics works. Right now, I'm manually checking the player's coordinates to see if the player is being squashed or not (view code down below).

### Explanation
Right now, I have 4 pre-set ceilings:
1. 
![ceiling_1](https://i.imgur.com/DN7KQzN.png)
2. 
![ceiling_2](https://i.imgur.com/7Ysonck.png)
3. 
![ceiling_3](https://i.imgur.com/UiyGAEL.png)
4. 
![ceiling_4](https://i.imgur.com/GwBGf9w.png)

These ceilings will be spawned one at a time randomly. Once it goes low enough, I check if the player gets squashed or not, but I do it manually:
```cs
void Update () {
  if (gameObject.transform.position.y <= -4.04 && gameObject.transform.position.y >= -4.30
  && player.transform.position.x >= -4.7 && player.transform.position.y <= -3.079) {
    Debug.Log ("SQUASHED");
  }
}
```
`gameObject` refers to the ceiling's game object. `player` refers to the player's game object.

The code works fine, but it only works for the first ceiling. If I want it to work for other ceilings, I need to hard code the same code differently for each ceiling.

There should be a better way to approach this issue. Instead of writing a script file for each ceiling, I want one file that can be associated with all four ceiling prefabs. Also, instead of hardcoding it, maybe using raycasts or collisions.

**Comment by willyngo** [comment]
We'll make the player check for collisions. Since trap elements come and go, it'll be resource heavy to always make them check for collisions. Also the player is always on the screen at all times. I'm working on it now, it should be up soon on my branch.

**Comment by willyngo** [comment]
A bit of detail on that player collision: The player will check for any collisions whose tag is 'Trap'. So make sure your trap elements have the 'Trap' tag. That way, your trap script only needs to worry about its own movement, no need to take care of the player.

**Comment by shifatkhan** [comment]
Ok, so we will check for collision. But how will we know that the player is being squashed between the ceiling and the floor? For example, the player could jump and hit its head on the ceiling, which will trigger the collision. However, the player is not being crushed at that moment. How do we bypass this?

**Comment by shifatkhan** [comment]
### Fix
I fixed the issue by adding another box collider on the bottom of the ceiling and set it as `isTrigger` while the box collider on top is not set to `isTrigger`. With this, I can use `OnTriggerEnter2D` whenever the player hits the bottom of the ceiling.

![ceiling_box_collider](https://i.imgur.com/8MG01KD.png)

All I have to do now is check if the player is grounded or not since that means that the player is between the ceiling and the floor.

```cs
void OnTriggerEnter2D(Collider2D other) {
  if (other.gameObject.tag.Equals ("Player")  && other.gameObject.transform.position.y <= -3.079) {
    Debug.Log ("SQUASHED");
  }
}
```
This code works for all of the prefab ceilings. I do not need to hardcode different cases for each ceiling. Thus, fixing the issue.

**Comment by shifatkhan** [comment]
Leaving this open in case someone finds better code for this.

**Comment by shifatkhan** [comment]
### Fix 2
I found out that the code mentioned above only works for a particular level where the player is `grounded` if the `y` coordinate of the ground is at `-3.079`.

The fix for this was simple. The `Player` script had a boolean `isAirborne` that states whether the player is grounded or not (for example, the player is standing on an object ---> `isAirborne = false`). The code:

```cs
void OnTriggerEnter2D(Collider2D other) {
  if (other.gameObject.tag.Equals ("Player") && !other.gameObject.GetComponent<Player>().isAirborne) {
    Debug.Log ("SQUASHED");
  }
}
```
This code is even better because the player can get squashed even if she wasn't on the ground (i.e.: standing on a barrel).

**Comment by shifatkhan** [comment]
We decided to go with a line of spike balls instead of ceilings since getting a game over from getting squashed sucks.
